<?php

return [
    'Symfony\Bundle\FrameworkBundle\FrameworkBundle' => ['all' => true],
    'Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle' => ['all' => true],
    'Symfony\Bundle\WebProfilerBundle\WebProfilerBundle' => ['dev' => true, 'test' => true],
    'Symfony\Bundle\TwigBundle\TwigBundle' => ['all' => true],
    'Symfony\Bundle\SecurityBundle\SecurityBundle' => ['all' => true],
    'Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle' => ['all' => true],
    'Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle' => ['all' => true],
    'Doctrine\Bundle\DoctrineBundle\DoctrineBundle' => ['all' => true],
    'JavierEguiluz\Bundle\EasyAdminBundle\EasyAdminBundle' => ['all' => true],
    'Symfony\Bundle\DebugBundle\DebugBundle' => ['dev' => true, 'test' => true],
    'Endroid\CmSms\Bundle\CmSmsBundle\EndroidCmSmsBundle' => ['all' => true],
    'Endroid\Flusher\Bundle\FlusherBundle\EndroidFlusherBundle' => ['all' => true],
    'Endroid\Guide\Bundle\GuideBundle\EndroidGuideBundle' => ['all' => true],
    'Endroid\Import\Bundle\ImportBundle\EndroidImportBundle' => ['all' => true],
    'Endroid\Import\Bundle\ImportDemoBundle\EndroidImportDemoBundle' => ['dev' => true],
    'Endroid\QrCode\Bundle\QrCodeBundle\EndroidQrCodeBundle' => ['all' => true],
    'Endroid\SoccerCalendar\Bundle\SoccerCalendarBundle\EndroidSoccerCalendarBundle' => ['all' => true],
    'FOS\UserBundle\FOSUserBundle' => ['all' => true],
    'Sonata\DatagridBundle\SonataDatagridBundle' => ['all' => true],
    'Sonata\CoreBundle\SonataCoreBundle' => ['all' => true],
    'Sonata\BlockBundle\SonataBlockBundle' => ['all' => true],
    'Knp\Bundle\MenuBundle\KnpMenuBundle' => ['all' => true],
    'Sonata\AdminBundle\SonataAdminBundle' => ['all' => true],
    'Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle' => ['all' => true],
    'HWI\Bundle\OAuthBundle\HWIOAuthBundle' => ['all' => true],
];
