<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Endroid\Bundle\PusherBundle\EndroidPusherBundle::class => ['all' => true],
    Endroid\CmSms\Bundle\CmSmsBundle\EndroidCmSmsBundle::class => ['all' => true],
    Endroid\DataSanitize\Bundle\DataSanitizeBundle\EndroidDataSanitizeBundle::class => ['all' => true],
    Endroid\DataSanitize\Bundle\DataSanitizeDemoBundle\EndroidDataSanitizeDemoBundle::class => ['all' => true],
    Endroid\Flusher\Bundle\FlusherBundle\EndroidFlusherBundle::class => ['all' => true],
    Endroid\Guide\Bundle\GuideBundle\EndroidGuideBundle::class => ['all' => true],
    Endroid\Import\Bundle\ImportBundle\EndroidImportBundle::class => ['all' => true],
    Endroid\Import\Bundle\ImportDemoBundle\EndroidImportDemoBundle::class => ['all' => true],
    Endroid\PredictionIO\Bundle\PredictionIOBundle\EndroidPredictionIOBundle::class => ['all' => true],
    Endroid\PredictionIO\Bundle\PredictionIODemoBundle\EndroidPredictionIODemoBundle::class => ['all' => true],
    Endroid\QrCode\Bundle\QrCodeBundle\EndroidQrCodeBundle::class => ['all' => true],
    Endroid\SoccerCalendar\Bundle\SoccerCalendarBundle\EndroidSoccerCalendarBundle::class => ['all' => true],
    Endroid\Tile\Bundle\TileBundle\EndroidTileBundle::class => ['all' => true],
    FOS\UserBundle\FOSUserBundle::class => ['all' => true],
    Sonata\DatagridBundle\SonataDatagridBundle::class => ['all' => true],
    Sonata\CoreBundle\SonataCoreBundle::class => ['all' => true],
    Sonata\BlockBundle\SonataBlockBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    Sonata\AdminBundle\SonataAdminBundle::class => ['all' => true],
    Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle::class => ['all' => true],
    HWI\Bundle\OAuthBundle\HWIOAuthBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['all' => true],
    FOS\OAuthServerBundle\FOSOAuthServerBundle::class => ['all' => true],
    FOS\RestBundle\FOSRestBundle::class => ['all' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    Nelmio\ApiDocBundle\NelmioApiDocBundle::class => ['all' => true],
];
